[connections] # Database connections
mongo = "mongodb://mongo:27017"

[bot] # bot settings
reload_flag = false
command_flag = 30
intents_flag = 3276799
activity_str = "The Ducks"
activity_type = 3
owner_ids = [111111111111111111] # replace with owner ids or leave blank for auto
test_guilds = [111111111111111111, 111111111111111111]  # Test guilds register commands faster
dev_guilds = [111111111111111111, 111111111111111111]   # Dev guilds have dev commands enabled, and provide debugging tools

[keys] # some default credentials for bundled services
wavelink = { host = "lavalink", port = 2333, password = "youshallnotpass" } # wavelink cog may accept a link to enable connection to multiple nodes
# wavelink = [{ host = "lavalink", port = 2333, password = "youshallnotpass" },{ host = "lavalink2", port = 2333, password = "youshallpass" }]
snekbox = { url = "http://snekbox:8060" }
piston = { url = "https://emkc.org/" }


[dir] # directories for various cogs
music = { name = "music", path = "./music", data = { data = "..." } } # No longer required, but cog may be renabled at anytime
temp = { name = "temp", path = "./temp" }

[patches] # Patches toggle various patches typically changing loggers
wavelink = false # patches loggers in wavelink to enable logging

[logging.cogs]
level = 10
    # logging levels - See src/helper/settings.py:22 for levels
    # ERROR = 40
    # INFO = 20
    # DEBUG = 10
[logging.disnake]
logfile = "./disnake.log" # defining logfile will enable logging to file
encoding = "utf-8" # the default encoding method may be changed
level = 40
