version: '3'

services:
  bot:
    image: ghcr.io/stinky-c/datbot:latest
    volumes:
      - ./config.toml:/app/config.toml:rw

    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN} # Set to the bot token
    networks:
      - internal
    links:
      - "mongo:mongo"
      - "snekbox:snekbox"
      - "lavalink:lavalink"

    depends_on:
      lavalink:
        condition: service_healthy
      snekbox: {}
      mongo: {}

  mongo:
    image: mongo
    networks:
      - internal

  snekbox:
    image: ghcr.io/python-discord/snekbox:2023.3.13.0
    networks:
      - internal
    ipc: none
    privileged: true

  lavalink:
    image: fredboat/lavalink:3.7.5
    networks:
      - internal
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:rw

networks:
  internal: {}
