version: '3'

services:
  bot-dev:
    build: .
    networks:
      - internal
    volumes:
      - ./config.toml:/app/config.toml:rw
      - ./.env:/app/.env:rw
      - ./.ignored/music:/app/music:rw
      - ./.ignored/temp:/app/temp:rw
      - ./src/cogs:/app/cogs:rw
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - "lavalink:lavalink"
      - "snekbox:snekbox"
      # - "mcrouter:mcrouter"
    depends_on:
      - lavalink
      # - mcrouter
      - snekbox

  lavalink:
    image: fredboat/lavalink:3.7.8
    networks:
      - internal
    volumes:
      - ./.ignored/application.yml/:/opt/Lavalink/application.yml:rw

  snekbox:
    image: ghcr.io/python-discord/snekbox:latest
    networks:
      - internal
    ipc: none
    privileged: true


  #? WIP
  # mcrouter:
  #   image: itzg/mc-router
  #   environment:
  #     API_BINDING: ":25564"
  #   networks:
  #     - internal
  #     - mcserver
  #   ports:
  #     - 25565:25565

networks:
  internal: {}
  # mcserver:
  #   external: true
